# @package _global_

env:
  shortname: cartpole
  name: CartPole-v1
  demo: CartPole-v1_1000 # Expert demo containing upto 1000 trajectories
  cond: cartpole.pkl
  learn_steps: 1e5
  eval_interval: 1e3

expert:
  demos: 1
  subsample_freq: 20

eval:
  policy: 
  threshold: 500

q_net:
  _target_: agent.softq_models.OfflineQNetwork

log_interval: 500